### ISSUE TITLE
semseeker: error in sample sheet columns

### ISSUE THREAD

**Issue by sandrogmb** [drake69/semseeker#1]
Ciao Luigi,
sono Sandro. 
Ho provato a installare semseeker (e tutti i pacchetti necessari). Ho modificato il mio sample_sheet che adesso ha le seguenti colonne:

> colnames(sample_sheet)
[1] "Sample_ID"        "Sentrix_ID"       "Sentrix_Position" "titles_samples"   "gender"           "age"              "Sample_Group"    
[8] "diet"             "Basename"  

poi lancio champ e non mi dà alcun errore.

Quindi lancio il codice con i comandi di semseeker

```{r, echo=FALSE}
library(semseeker)

normalizedData <- readRDS("~/normalizedData.rds")

sampleSheet <- read.csv2("./sample_sheet.csv")

semseeker (sampleSheet = sampleSheet, 
        methylationData = normalizedData,
        resultFolder = "~/semseeker_result/")
```
e i nomi delle colonne diventano questi:

> colnames(sampleSheet)
[1] "Sample_ID.Sentrix_ID.Sentrix_Position.titles_samples.gender.age.Sample_Group.diet.Basename"

cioé sampleSheet è diventato un df con un'unica colonna!
e si blocca tutto dando il seguente errore:

Error in semseeker(sampleSheet = sampleSheet, methylationData = normalizedData, : Lost following columns Sample_IDSample_Group 2022-01-28 14:13:20Especting a column with name Sample_Group and possible values Reference, Control and Case

Sai aiutarmi?

**Comment by drake69** [comment]
Più che un problema di semseeker mi sembra un problema di sample sheet, verifica il separatore usato nella sample sheet ed usa il parametro sep in read.csv2

**Comment by sandrogmb** [comment]
- ok grazie del suggerimento, effettivamente usando sep="," non dà più problemi


- segnalo che ho dovuto modificare il sampleSheet con le categorie del sample_group control/case (e poi è andato avanti)

- però l'esecuzione non si conclude:
Non capisco perché mi dice Empty methylationData dato che normalizedData è un df che ha le caratteristiche che puoi vedere di seguito (quindi non è vuoto):

Empty methylationData 2022-01-29 12:44:33
Error in semseeker(sampleSheet = sampleSheet, methylationData = normalizedData,  : 
  Empty methylationData 
> View(normalizedData)
> colnames(normalizedData)
 [1] "GSM3323567" "GSM3323568" "GSM3323569" "GSM3323570" "GSM3323571" "GSM3323572" "GSM3323573" "GSM3323574" "GSM3323575" "GSM3323576" "GSM3323577"
[12] "GSM3323578"
> dim(normalizedData)
[1] 406292     12
>normalizedData[1,]
GSM3323567 GSM3323568 GSM3323569 GSM3323570 GSM3323571 GSM3323572 GSM3323573 GSM3323574 GSM3323575 GSM3323576 GSM3323577 GSM3323578 
 0.8143751  0.8182624  0.8132550  0.8440887  0.8005077  0.7700170  0.8183217  0.8362134  0.8280561  0.8040925  0.8148890  0.7863636 

Grazie!

**Comment by drake69** [comment]
Grazie a te per la segnalazione, ho modificato le istruzioni perchè mancavano di un dettaglio: la samplesheet deve avere una colonna Population che ammette tre valori Case,Control e Reference.
Se non si ha una popolazione di riferimento si possono ripetere le riche dei controlli e mettere il valor Reference nella colonna Population.

**Comment by sandrogmb** [comment]
scusa ancora non riesco a capire perché mi dà questo errore anche dopo aver aggiunto la colonna population con i valori "case" per i campioni dopo il trattamento e "control" per i campioni pre-trattamento (se è corretto).

Error in semseeker(sampleSheet = sampleSheet, methylationData = normalizedData, :
Empty methylationData

grazie!

**Comment by drake69** [comment]
Eh sì, hai messo il dito nella piaga ;-), errore di documentazione, grazie per la segnalazione. Ho corretto, la colonna deve essere Sample_Group.

**Comment by sandrogmb** [comment]
forse l'"undefined" dell'errore dipende dal fatto che nel sample_id il nome delle colonne è raddoppiato perché ci sono i due canali rosso e verde?

**Comment by drake69** [comment]
Ma scusa hai rispettato le maiuscole, Sample_Group e Sample_ID i nomi delle colonne nei data frame sono case sensitive.
Lo stesso per le categorie di Sample_Group sono case sensitive, Reference, Case, Control
L.

**Comment by sandrogmb** [comment]
Ciao Luigi
allora io ho rispettato le maiuscole e ho costruito due colonne nel sample sheet una Sample_Group e una Population in cui ho inserito le categorie Case e Reference al posto di Control (le maiuscole sono rispettate nel mio sampleSheet come puoi vedere di segutio).
> sampleSheet
    Sample_ID   Sentrix_ID Sentrix_Position titles_samples gender age Sample_Group         diet                     Basename Population
1  GSM3323567 200251580170           R01C01            ID1   Male  52    Reference  Pre GF Diet  10005833149_R03C01_Grn.idat  Reference
2  GSM3323568  10005833149           R03C01            ID2 Female  38    Reference  Pre GF Diet  10005833149_R03C01_Red.idat  Reference


Secondo me se il problema fosse questo che dici l'esecuzione si fermerebbe al seguente controllo (righe 81-88 della funzione semseeker.R):
# reference population
  populations <-  c("Reference","Control","Case")
  sampleSheet$Sample_Group <- R.utils::toCamelCase(tolower(sampleSheet$Sample_Group), capitalize=TRUE)
  sampleSheet$Sample_Group <- as.factor(sampleSheet$Sample_Group)
  matchedPopulation <- levels(sampleSheet$Sample_Group) %in% populations
  if (is.element(FALSE, matchedPopulation)) {
    stop("File:",sampleSheetPath, " Sample_Group should contain only: Reference, Control, Case")
  }

Invece mi dice "undefined columns".
Però ho anche provato a fare le seguenti prove.

##DUBBIO
Siccome la funzione semseeker ha il seguente frammento di codice con ciclo for (già segnalato prima):

for (populationName in populations) {

....
populationMatrixColumns <- colnames(methylationData[, populationSampleSheet$Sample_ID])

....
}

Provo a riprodurre sui miei dati i risultati di questo ciclo for:

1. prendo gli ID del mio sampleSheet e gli ID sono 24 come puoi vedere (12 campioni per ogni colore rosso e verde)
> ID_sampleSheet<-sampleSheet$Sample_ID
> ID_sampleSheet
 [1] "GSM3323567" "GSM3323568" "GSM3323569" "GSM3323570" "GSM3323571" "GSM3323572" "GSM3323573" "GSM3323574" "GSM3323575" "GSM3323576" "GSM3323577"
[12] "GSM3323578" "GSM3323567" "GSM3323568" "GSM3323569" "GSM3323570" "GSM3323571" "GSM3323572" "GSM3323573" "GSM3323574" "GSM3323575" "GSM3323576"
[23] "GSM3323577" "GSM3323578"

> colonne <- colnames(file_dati[, ID_sampleSheet])
> prova<-file_dati[,colonne]
> dim(prova)
[1] 406292     24

Cioè in questo df ci sono 24 colonne ma con solo 12 nomi quindi è possibile che quando analizedData parte non sa quale colonna prendere di ciascuna delle 12 coppie.


##DOMANDA
MA NON E' CHE POTRESTI FARMI VEDERE COME HAI COSTRUITO TU UN SAMPLE SHEET E SU QUALI DATI HAI FATTO GIRARE UN'ANALISI CHE E' ARRIVATA A TERMINE?

grazie
CIAO

**Comment by drake69** [comment]
Ottimo suggerimento, faccio uno script di test con una sample sheet e lo scaricamento dati da GEO.

**Comment by drake69** [comment]
Il problema non è in semseeker ma a monte, il dataframe dei dati di metilazione viene creato da ChAMP assegnando come valori di colonna la prima colonna della sample sheet, invece per semseeker il nome delle colonne del data frame di metilazione deve essere lo stesso del Sample_ID. Comunque ho migliorato il controllo in semseeker e caricato un esempio fiunzionante.

**Comment by sandrogmb** [comment]
Ciao Luigi,
non capisco cosa non vada.
Ho provato a lanciare lo script del tuo esempio.
il primo warning è inquietante però R non si blocca

WARNING: Population Reference is empty 2022-02-11 19:27:05


infatti l'analisi procede ma....

dopo un po' compare il seguente errore:

Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
In addition: Warning messages:
1: In utils::memory.limit(16000) : cannot decrease memory limit: ignored
2: In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): sampleSheet
3: In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): sampleSheet

tu hai idea del problema? a te l'esempio girava fino alla fine?
grazie
Sandro

**Comment by sandrogmb** [comment]
ciao Luigi
l'analisi del tuo esempio è arrivata finalmente a termine.
Ho dato un'occhiata ai grafici che a meno che non ci sia qualche  mia svista sono tutte delle heatmap. Mi aspettavo un grafico tipo boxplot con in evidenza gli outlier che superano i limiti definiti tipo livello di espressione +/- 3ds oltre la mediana (come nella definizione dell'articolo di gentilini). Inoltre non so ma non ho trovato da nessuna parte la soglia che usi per definire un outlier all'interno della descrizione del pacchetto (non sono andato a vedere il codice ma forse nella descrizione andrebbe scritto).
Le cartelle inference ed euristic sono vuote, è corretto?
grazie
ciao
s

**Comment by sandrogmb** [comment]
ciao Luigil'analisi del tuo esempio è arrivata finalmente a termine.Ho dato un'occhiata ai grafici che a meno che non ci sia qualche mia svista sono tutte delle heatmap. Mi aspettavo un grafico tipo boxplot con in evidenza gli outlier che superano i limiti definiti tipo livello di espressione. Inoltre non so ma non ho trovato da nessuna parte la soglia che usi per definire un outlier all'interno della descrizione del pacchetto (non sono andato a vedere il codice ma forse nella descrizione andrebbe scritto).Le cartelle inference ed euristic sono vuote, è corretto?grazieciaos Dott. Sandro ***@***.***   Da: Luigi CorsaroInviato: Sunday, February 6, 2022 1:54 PMA: drake69/semseekerCc: sandrogmb; AuthorOggetto: Re: [drake69/semseeker] semseeker: error in sample sheet columns (Issue #1) Ottimo suggerimento, faccio uno script di test con una sample sheet e lo scaricamento dati da GEO.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
